### 1. Login với email và mật khẩu
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test1000@gmail.com",
  "password": "123456"
}

### 2. Logout với sessionId
POST http://localhost:8080/auth/logout
Content-Type: application/json
Cookie: JSESSIONID=08154ECA196D0A304C8F64FCCCED02F1
