### 1. Login với email và mật khẩu
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "23110370@student.hcmute.edu.vn",
  "password": "123456"
}
### 1.2. Login với email và mật khẩu (rememberMe = 0)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "23110186@student.hcmute.edu.vn",
  "password": "123456",
  "rememberMe": 1
}
### 1.3. Login với email và mật khẩu (rememberMe = 0)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "23110296@student.hcmute.edu.vn",
  "password": "123456"
}

### 2. Logout với sessionId
POST http://localhost:8080/api/auth/logout
Content-Type: application/json
Cookie: JSESSIONID=08154ECA196D0A304C8F64FCCCED02F1
