### 1. Login với email và mật khẩu
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "vovantu22112005@gmail.com",
  "password": "vovantu"
}
### 1.2. Login với email và mật khẩu
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "quoc2@gmail.com",
  "password": "123456"
}

### 2. Logout với sessionId
POST http://localhost:8080/api/auth/logout
Content-Type: application/json
Cookie: JSESSIONID=08154ECA196D0A304C8F64FCCCED02F1
