### Upload file
POST http://localhost:8080/api/media/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Cookie: JSESSIONID=A54646E6AF2E0CAFB0E9D16886F5A157

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test2.jpg"
Content-Type: image/jpeg

< ./test.jpg
--WebAppBoundary--

### Get media
GET http://localhost:8080/media/files/20_e12016c4-7425-4c75-97fe-22c1709232ef_test.jpg
Cookie: JSESSIONID=8AB371EFF15A8A2CB1F2E254933018D2