### Danh sách bài đăng
GET http://localhost:8080/api/posts
Cookie: JSESSIONID=E0FEAD37E511E92C2ECE48245887EBB6

### Danh sách bài đăng phù hợp cho 1 user (self + friends + public)
GET http://localhost:8080/api/posts/suitable/3
Cookie: JSESSIONID=DC5A8A24ECB8D950968DF8AE657AA3A1

### Lấy bài đăng theo id
GET http://localhost:8080/api/posts/5

### Lấy bài đăng của user theo userId
GET http://localhost:8080/api/posts/user/1
Cookie: JSESSIONID=4060E5D2D409BB10FC7114A4DE5B1718

### Lấy bài đăng của FRIENDS của 1 user theo userId
GET http://localhost:8080/api/posts/friends/1
Cookie: JSESSIONID=F789F73C5CE44F0FAFA1C21D0B630642

### Lấy các bài đăng Public
GET http://localhost:8080/api/posts/public
Cookie: JSESSIONID=F789F73C5CE44F0FAFA1C21D0B630642

### Lấy các bài đăng Important
GET http://localhost:8080/api/posts/important
Cookie: JSESSIONID=75A8BFFFA89C6C3F5CF0ADEAF930E7A0

### Tạo 1 bài đăng (Với media)
POST http://localhost:8080/api/posts
Content-Type: application/json
Cookie: JSESSIONID=F789F73C5CE44F0FAFA1C21D0B630642

{
  "author_id": 1,
  "content": "Tôi đăng ảnh mới",
  "visibility": "public",
  "post_type": "normal",
  "status": "pending",
  "media": [
    { "media_type": "image", "media_url": "http://localhost:8080/media/files/1_7f2bfaf6-af56-4ae1-960c-87fabc1cab5c_test.jpg"},
    { "media_type": "image", "media_url": "http://localhost:8080/media/files/1_46e8d03d-6d54-4da9-86cc-7212f2514710_test2.jpg"}
  ]
}

### Tạo 1 bài đăng
POST http://localhost:8080/api/posts
Content-Type: application/json
Cookie: JSESSIONID=0ED90741E20F3A99FA6F2DE62C54BCF2

{
  "author_id": 1,
  "content": "Tôi đăng ảnh mới",
  "visibility": "public",
  "post_type": "normal",
  "status": "pending",
  "media": []
}

### Đăng bài đăng đặc biệt (important) - Chỉ special, admin mới được phép
POST http://localhost:8080/api/posts
Content-Type: application/json
Cookie: JSESSIONID=E14658C62FE6D024190A35DF7BD36C01

{
  "author_id": 14,
  "content": "Bài viết quan trọng nè 2",
  "visibility": "public",
  "post_type": "normal",
  "status": "pending",
  "media": [],
  "isImportant": true
}


### Cập nhật 1 bài đăng
PUT http://localhost:8080/api/posts/3
Content-Type: application/json
Cookie: JSESSIONID=7A64E70D3F4A3FEE99025AAE2555983D

{
  "content": "Nội dung đã được chỉnh sửa rồi ok",
  "visibility": "public",
  "post_type": "normal",
  "status": "pending",
  "media": [
    { "media_type": "image", "media_url": "http://example.com/image2.png" }
  ]
}

### Xóa 1 bài đăng
DELETE http://localhost:8080/api/posts/11
Cookie: JSESSIONID=4060E5D2D409BB10FC7114A4DE5B1718

### Reactions (Like/Reaction)
# Tạo reaction (like); LƯU Ý: Reaction nếu như đã tồn tại thì sẽ cập nhật lại
POST http://localhost:8080/api/posts/2/reactions
Cookie: JSESSIONID=142343DA77C62998C07E88F7498ACA43
Content-Type: application/json

{
  "user": { "id": 1 },
  "type": "like"
}

### Lấy tất cả reactions của post
GET http://localhost:8080/api/posts/2/reactions/all
Cookie: JSESSIONID=EE00B61B34D79A9DEA894E8D5FEDFDAC

### Xoá reaction (unlike) theo reaction id
DELETE http://localhost:8080/api/posts/1/reactions/1000

### Comments
# Lấy comment cho post (có thể thêm ?page=..&size=..)
GET http://localhost:8080/api/posts/2/comments
Cookie: JSESSIONID=F9F0885D63D75AAD505190E05F9B5454

### Lấy 1 comment theo id (mới)
GET http://localhost:8080/api/comments/4
Cookie: JSESSIONID=84AAE73AE6BB0DE81169BFF36A3DC0A2

### Tạo comment
POST http://localhost:8080/api/posts/2/comments
Cookie: JSESSIONID=2E2E9E4A3C0D1B98D51587D7D4131F4B
Content-Type: application/json

{
  "user": { "id": 2 },
  "content": "Rất hay luôn! 1"
}

### Tạo reply (comment lồng nhau)
POST http://localhost:8080/api/posts/1/comments
Content-Type: application/json

{
  "user": { "id": 2 },
  "content": "Cảm ơn bạn, mình trả lời ở đây",
  "parent_comment_id": 3
}

### Cập nhật comment
PUT http://localhost:8080/api/posts/4/comments/2
Content-Type: application/json
Cookie: JSESSIONID=1DC7391AE19B9D149B943782253E090F

{
  "content": "Điệp đẹp trai nhất"
}

### Xoá comment
DELETE http://localhost:8080/api/posts/4/comments/3
Cookie: JSESSIONID=1DC7391AE19B9D149B943782253E090F

### Shares (Chia sẻ bài viết)
  
# Tạo 1 share (server sẽ lấy user từ session; không cần gửi user_id)
POST http://localhost:8080/api/posts/8/shares
Content-Type: application/json
Cookie: JSESSIONID=EC1378CF5F48B4B623AC37600464AEEC

{
  "shared_text": "Mình chia sẻ bài này nha ok nha cu",
  "visibility": "friend"
}

### Lấy danh sách share của 1 post
GET http://localhost:8080/api/posts/6/shares
Cookie: JSESSIONID=EC1378CF5F48B4B623AC37600464AEEC

### Lấy 1 share theo id
GET http://localhost:8080/api/posts/6/shares/7
Cookie: JSESSIONID=4CB18DE274EB54A8E4A1D27E20DB351A

### Xoá 1 share (chỉ owner hoặc admin)
DELETE http://localhost:8080/api/posts/6/shares/8
Cookie: JSESSIONID=EC1378CF5F48B4B623AC37600464AEEC

### Cập nhật 1 share (chỉ owner được phép chỉnh sửa shared_text và visibility)
PUT http://localhost:8080/api/posts/9/shares/17
Content-Type: application/json
Cookie: JSESSIONID=844C5D5D724CFC6F30B765753A860CDA

{
  "shared_text": "chán quá hạ em, tội nghiệp",
  "visibility": "friend"
}

