### Danh sách bài đăng
GET http://localhost:8080/posts
Cookie: JSESSIONID=AF26CCD55A6F65EF04A080D94F1A6D27

### Lấy bài đăng theo id
GET http://localhost:8080/posts/5

### Tạo 1 bài đăng
POST http://localhost:8080/posts
Content-Type: application/json
Cookie: JSESSIONID=4F3E4D3ACC716E1DC9E67A77FB075DD5

{
  "author_id": 20,
  "content": "Tôi đăng ảnh mới",
  "visibility": "friends",
  "post_type": "normal",
  "status": "pending",
  "media": [
    { "media_type": "image", "media_url": "http://example.com/image.png"},
    { "media_type": "image", "media_url": "http://example.com/image2.png"}
  ]
}

### Cập nhật 1 bài đăng
PUT http://localhost:8080/posts/8
Content-Type: application/json

{
  "content": "Nội dung đã được chỉnh sửa rồi ok",
  "visibility": "public",
  "post_type": "normal",
  "status": "approved",
  "media": [
    { "media_type": "image", "media_url": "http://example.com/image2.png" }
  ]
}

### Xóa 1 bài đăng
DELETE http://localhost:8080/posts/16

### Reactions (Like/Reaction)
# Tạo reaction (like)
POST http://localhost:8080/posts/1/reactions
Content-Type: application/json

{
  "user": { "id": 1 },
  "type": "love"
}

### Lấy tất cả reactions của post
GET http://localhost:8080/posts/1/reactions

### Xoá reaction (unlike) theo reaction id
DELETE http://localhost:8080/posts/1/reactions/16

### Comments
# Lấy comment cho post (có thể thêm ?page=..&size=..)
GET http://localhost:8080/posts/1/comments

### Tạo comment
POST http://localhost:8080/posts/5/comments
Content-Type: application/json

{
  "user": { "id": 2 },
  "content": "Rất hay luôn!"
}

### Tạo reply (comment lồng nhau)
POST http://localhost:8080/posts/1/comments
Content-Type: application/json

{
  "user": { "id": 2 },
  "content": "Cảm ơn bạn, mình trả lời ở đây",
  "parent_comment_id": 3
}

### Cập nhật comment
PUT http://localhost:8080/posts/2/comments/4
Content-Type: application/json

{
  "content": "Sửa lại nội dung comment ok nha"
}

### Xoá comment
DELETE http://localhost:8080/posts/5/comments/7

### Shares (Chia sẻ bài viết)
# Tạo 1 share 
POST http://localhost:8080/posts/5/shares
Content-Type: application/json

{
  "user_id": 2,
  "shared_text": "Mình chia sẻ bài này nha",
  "visibility": "public"
}



### Lấy danh sách share của 1 post
GET http://localhost:8080/posts/5/shares

### Xoá 1 share
DELETE http://localhost:8080/posts/5/shares/4
