### Danh sách bài đăng
GET http://localhost:8080/api/posts
Cookie: JSESSIONID=79C1A7C354F95DDD02F904942914C952

### Lấy bài đăng theo id
GET http://localhost:8080/api/posts/5

### Tạo 1 bài đăng
POST http://localhost:8080/api/posts
Content-Type: application/json
Cookie: JSESSIONID=A54646E6AF2E0CAFB0E9D16886F5A157

{
  "author_id": 1,
  "content": "Tôi đăng ảnh mới",
  "visibility": "friends",
  "post_type": "normal",
  "status": "pending",
  "media": [
    { "media_type": "image", "media_url": "http://localhost:8080/media/files/1_7f2bfaf6-af56-4ae1-960c-87fabc1cab5c_test.jpg"},
    { "media_type": "image", "media_url": "http://localhost:8080/media/files/1_46e8d03d-6d54-4da9-86cc-7212f2514710_test2.jpg"}
  ]
}

### Cập nhật 1 bài đăng
PUT http://localhost:8080/posts/8
Content-Type: application/json

{
  "content": "Nội dung đã được chỉnh sửa rồi ok",
  "visibility": "public",
  "post_type": "normal",
  "status": "approved",
  "media": [
    { "media_type": "image", "media_url": "http://example.com/image2.png" }
  ]
}

### Xóa 1 bài đăng
DELETE http://localhost:8080/posts/16

### Reactions (Like/Reaction)
# Tạo reaction (like)
POST http://localhost:8080/posts/1/reactions
Content-Type: application/json

{
  "user": { "id": 1 },
  "type": "love"
}

### Lấy tất cả reactions của post
GET http://localhost:8080/posts/1/reactions

### Xoá reaction (unlike) theo reaction id
DELETE http://localhost:8080/posts/1/reactions/16

### Comments
# Lấy comment cho post (có thể thêm ?page=..&size=..)
GET http://localhost:8080/posts/1/comments

### Tạo comment
POST http://localhost:8080/posts/5/comments
Content-Type: application/json

{
  "user": { "id": 2 },
  "content": "Rất hay luôn!"
}

### Tạo reply (comment lồng nhau)
POST http://localhost:8080/posts/1/comments
Content-Type: application/json

{
  "user": { "id": 2 },
  "content": "Cảm ơn bạn, mình trả lời ở đây",
  "parent_comment_id": 3
}

### Cập nhật comment
PUT http://localhost:8080/posts/2/comments/4
Content-Type: application/json

{
  "content": "Sửa lại nội dung comment ok nha"
}

### Xoá comment
DELETE http://localhost:8080/posts/5/comments/7

### Shares (Chia sẻ bài viết)
# Tạo 1 share 
POST http://localhost:8080/posts/5/shares
Content-Type: application/json

{
  "user_id": 2,
  "shared_text": "Mình chia sẻ bài này nha",
  "visibility": "public"
}



### Lấy danh sách share của 1 post
GET http://localhost:8080/posts/5/shares

### Xoá 1 share
DELETE http://localhost:8080/posts/5/shares/4
