### Home
GET http://localhost:8080

### API lấy các users
GET http://localhost:8080/users

### API tạo user (đăng kí user mới)
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "fullName": "Diep",
  "email": "diep@example.com",
  "passwordHash": "123456",
  "role": "student"
}

### API thay đổi full name
POST http://localhost:8080/users/change-fullname
Content-Type: application/json

{
  "id": 1,
  "fullName": "Tú"
}

### API cập nhật toàn bộ thông tin User
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "fullName": "Jane Smith",
  "email": "jane.smith@example.com",
  "passwordHash": "newHash",
  "firstName": "Jane",
  "lastName": "Smith",
  "gender": "female",
  "dateOfBirth": "2001-05-10",
  "avatarUrl": "https://example.com/avatar.jpg",
  "coverPhotoUrl": "https://example.com/cover.jpg",
  "bio": "Hello, I am Jane",
  "schoolId": "SV20201234",
  "academicYear": "2020-2024",
  "role": "student",
  "phone": "+84-912345678",
  "website": "https://janesmith.dev",
  "country": "Vietnam",
  "city": "HCMC",
  "education": "HCMUTE",
  "workplace": "Intern at ACME",
  "facebookUrl": "https://facebook.com/jane",
  "instagramUrl": "https://instagram.com/jane",
  "linkedinUrl": "https://linkedin.com/in/jane",
  "twitterUrl": "https://twitter.com/jane",
  "lastSeenAt": "2025-09-12T10:00:00Z"
}

