### Home
GET http://localhost:8080

### API lấy các users
GET http://localhost:8080/users

### API tạo user (đăng kí user mới)
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john6@example.com",
  "passwordHash": "123456",
  "role": "student"
}

### API thay đổi full name
POST http://localhost:8080/users/change-fullname
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john6@example.com",
  "passwordHash": "123456",
  "newName": "John Smith"
}

